version: '3'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:17.1-alpine3.20
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "PGDATA=${PG_DATA}"
      #"PGPORT=${PG_PORT}"
    ports:
      - "${PG_PORT}:5432" #внешний порт:внутренний порт (постгрес подмается внутри контейнера на порут 5432)
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg  